language: python
python:
        - "3.6"
cache:
        apt: true
        directories:
                - $HOME/.ccache
env:
        - BUILD_NAME=python3
        - DETAILS=""


before_install:
        - ./gdal/ci/travis/${BUILD_NAME}/install.sh
        - sudo apt-get install -y libspatialindex-dev
        - sudo apt-get install -y libgdal1-dev
        - ./gdal/ci/travis/${BUILD_NAME}/before_install.sh 

cache: pip
install:
        - pip install -r requirements.txt
script:
        - python travis_tests.py

